### ISSUE TITLE
Choosing external API-s

### ISSUE THREAD

**Issue by AndreyDmitriev39r** [AndreyDmitriev39r/random-quote-machine-v2#5]
**_This issue does not require any codebase changes._**

**_Several people can work on this issue at once._**

Research the web and pick some API-s from where we can fetch various quotes.

For example, https://zenquotes.io/ can be used to get some inspirational quotes.

Share results of your efforts in this issue thread.

It can be simple list with API links and short explanation, which type of quotes you want to get from there.

**_You do not need to test those API-s or dive deep into their documentation. Your task is provide some initial info to work with, after we will choose exact API-s to use_**.

This issue will be closed when we will decide on API set.

**Comment by dgupta0** [comment]
https://api-ninjas.com/api/quotes -has categories too

**Comment by AndreyDmitriev39r** [comment]
#15 is related to zenquotes, tasks for other APIs will follow. Actually everyone who wnats can create similar ones and self-assign to them as well.

**Comment by MaximusI30** [comment]
[Images](https://unsplash.com/developers) - cool image API we could use to fetch a dynamic background image.

**Comment by AndreyDmitriev39r** [comment]
> https://api-ninjas.com/api/quotes -has categories too

good stuff, when looking into it, actually discovered that it has all the things to established all intended functionality in terms of fetching quotes!

**Comment by AndreyDmitriev39r** [comment]
> [Images](https://unsplash.com/developers) - cool image API we could use to fetch a dynamic background image.

as discussed on discord, there is a little chance that we need images API, but unsplash is cool resource, for getting images links also
